[package]
name = "barium-client"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11"
rand = "0.7"
rsa = { version = "0.2", features = [ "serde1" ] }
bincode = "1.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
dirs = "2.0"
native-tls = "0.2"
barium-shared = { path = "../shared" }

[build-dependencies]
regex = "1.3"
last-git-commit = "0.1"
