[package]
name = "barium-server"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = [ "tcp", "rt-core", "rt-threaded", "macros", "io-util" ] }
tokio-tls = "0.3"
native-tls = "0.2"
padlock = "0.1.1-alpha"
