[package]
name = "barium-server"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = [ "rt-core", "rt-threaded", "macros" ] }
padlock = "0.1.1-alpha"
barium-shared = { path = "../shared" }
bincode = "1.2"
log = "0.4"
fern = { version = "0.5", features = [ "colored" ] }
chrono = "0.4"
rsa = "0.2"
