name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: olback/rust-gtk-linux
      volumes:
        - volume/:/home/circleci/project

    steps:
    - name: Build
      run: cargo test
