name: Docker Linux Client

on: [push]

jobs:
  Docker:

    runs-on: ubuntu-latest
    container:
      image: olback/rust-gtk-linux
      volumes:
        - /home/runner/work/barium/barium:/home/circleci/project
      options: --workdir "/home/circleci/project"

    steps:
    - uses: actions/checkout@v1

    - name: list
      run: |
        whoami
        pwd
        ls -la .
        sudo mkdir /github/home/.rustup
        sudo chmod 777 -R /github/home/

    - name: Use Stable as Default
      run: sudo rustup default stable

    - name: Show Versions
      run: |
        rustc --version --verbose
        rustup --version
        cargo --version --verbose

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
      working-directory: /__w/barium/barium
