name: Docker Linux Client

on: [push]

jobs:
  Docker:

    runs-on: ubuntu-latest
    container:
      image: olback/rust-gtk-linux
      volumes:
        - /home/runner/work/barium/barium:/home/circleci/project
      env:
        CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v1

    - name: Use Stable as Default
      run: sudo rustup default stable

    - name: Show Versions
      run: |
        sudo rustc --version --verbose
        sudo rustup --version
        sudo cargo --version --verbose

    - name: list
      run: |
        whoami
        pwd
        ls -la .
        sudo mkdir /github/home/.rustup
        sudo chmod 777 -R /github/home/

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
      working-directory: /__w/barium/barium
